apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: quiz
  labels:
    app: quiz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz
  template:
    metadata:
      labels:
        app: quiz
    spec:
      containers:
        - name: main
          image: josefuentes/quiz:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: quiz
  labels:
    app: quiz
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: quiz
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: quiz
  name: quiz
spec:
  rules:
  - host: quiz.arp4.net
    http:
      paths:
      - backend:
          serviceName: quiz
          servicePort: 8080
        path: /
